name: Demo workflow

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  smoke_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print hi
      run: echo "Hi"
      shell: bash
  regression_test_job:
    runs-on: ubuntu-latest
    steps:
      - name: print bye
      run: echo "Bye"
      shell: bash
